export const FLOORS = [100, 1000, 10000, 100000];

export const STYLINGS = [
    "bold",
    "italics",
    "strikethrough",
    "underline",
    "backgroundColorRed",
    "backgroundColorGreen",
    "backgroundColorCyan",
    "backgroundColorRed",
    "backgroundColorOrange",
    "backgroundColorPurple",
    "backgroundColorBlack",
    "fontSize12",
    "fontSize14",
    "fontSize16",
    "fontSize18",
    "fontSize20",
    "fontSize22",
    "fontSize26",
    "fontSize30",
    "fontSize36",
    "fontSize44",
    "fontSize52",
];
